"""Oct 1–7, 2026 ACLSMED carousels (1080x1350). Clinical content aligned to AHA 2025 Guidelines."""
from engine.brand import CYAN, ECG_GREEN, RED, YELLOW

G = ECG_GREEN

C1 = {"id": "C1_hs_and_ts", "slides": [
    [("kicker", "PEA  ·  ASYSTOLE"), ("title", "The *H's & T's*:\n10 causes of arrest you can actually *fix*", 76),
     ("ecg", "sinus", {"hr": 74}, "II  ·  NO PULSE", G, 250, 5),
     ("body", "Organized rhythm, no pulse. Epinephrine buys time. *Fixing the cause* gets ROSC."), ("swipe",)],
    [("kicker", "THE H's", CYAN),
     ("rows", [("Hypovolemia", "Bleeding, trauma, GI bleed, flat neck veins", "Volume / blood, stop the bleed"),
               ("Hypoxia", "Airway problem, respiratory arrest first", "Oxygen, confirm airway & ventilation"),
               ("Hydrogen ion (acidosis)", "DKA, renal failure, prolonged downtime", "Ventilate; bicarb per protocol"),
               ("Hypo- / Hyperkalemia", "Dialysis patient, *peaked T, wide QRS*", "HyperK: calcium, shift, remove"),
               ("Hypothermia", "Cold exposure, drowning", "Active rewarming")])],
    [("kicker", "THE T's", CYAN),
     ("rows", [("Tension pneumothorax", "Trauma or ventilated, absent breath sounds, JVD", "Needle decompression → chest tube"),
               ("Tamponade (cardiac)", "Post-cardiac surgery, JVD, muffled heart sounds", "Pericardiocentesis / reopen"),
               ("Toxins", "Overdose history, *wide QRS* (TCA), pinpoint pupils", "Antidote; call poison control"),
               ("Thrombosis: pulmonary", "Sudden collapse, DVT risk, dilated RV", "Consider fibrinolytics"),
               ("Thrombosis: coronary", "Chest pain / STEMI before arrest", "Reperfusion: cath lab")])],
    [("kicker", "BEDSIDE MOVE", YELLOW), ("title", "Say them *out loud*\nevery 2-minute cycle", 72),
     ("bullets", ["Team leader reads the list; the team answers *ruled out* or *treating*",
                  "Ask: what happened *right before* the arrest?",
                  "Check the chart: K+, glucose, ABG, meds, recent procedures",
                  "Ultrasound at pulse checks can spot *tamponade, RV strain, pneumothorax*, only if it doesn't lengthen the pause"],
      38),
     ("callout", "Pulse checks stay *under 10 seconds*, even with a probe on the chest.", YELLOW)],
    [("kicker", "MEMORY HOOK"), ("title", "5 H's  +  5 T's", 84),
     ("pairs", ["THE H's", "THE T's"],
      [("Hypovolemia", "Tension pneumo"), ("Hypoxia", "Tamponade"), ("H+ (acidosis)", "Toxins"),
       ("Hypo/Hyper-K+", "Thrombosis: PE"), ("Hypothermia", "Thrombosis: MI")]),
     ("body", "Screenshot this slide for your badge buddy.", 36)],
    [("cta",)],
]}

C2 = {"id": "C2_stable_vs_unstable_tachy", "slides": [
    [("kicker", "TACHYCARDIA WITH A PULSE"), ("title", "Stable or *unstable?*\nThe 5 signs that decide\nshock vs. drugs", 72),
     ("ecg", "svt", {"hr": 188}, "II  ·  HR 188", G, 230, 4), ("swipe",)],
    [("kicker", "ASK FIRST", CYAN), ("title", "Is the fast rate *causing* the symptoms?", 70),
     ("body", "Rates under *150/min* rarely cause instability on their own. Look for another cause (sepsis, bleeding, pain, hypoxia)."),
     ("callout", "Pulseless? Stop. That's the *cardiac arrest* algorithm, not this one.", RED)],
    [("kicker", "UNSTABLE IF ANY OF THESE"),
     ("rows", [("1 · Hypotension", "Low BP, weak pulses", "Perfusion is failing"),
               ("2 · Acutely altered mental status", "New confusion, drowsy, agitated", "Brain isn't perfused"),
               ("3 · Signs of shock", "Cool, clammy, mottled, low urine output", "Tissue isn't perfused"),
               ("4 · Ischemic chest discomfort", "Pressure, pain, ST changes", "Heart isn't perfused"),
               ("5 · Acute heart failure", "Crackles, hypoxia, pulmonary edema", "Pump is failing")])],
    [("kicker", "UNSTABLE  →  SHOCK IT"), ("title", "*Synchronized*\ncardioversion", 84),
     ("bullets", ["Sedate if possible, but *don't delay* for a crashing patient",
                  "Press *SYNC*, look for markers on each R wave, and re-check after *every* shock",
                  "AFib: first shock *at least 200 J* biphasic (AHA 2025)",
                  "Atrial flutter: *200 J* may be reasonable",
                  "Other rhythms: use your *device-specific* energy"], 38)],
    [("kicker", "STABLE  →  GET A 12-LEAD", CYAN),
     ("table", ["QRS / RHYTHM", "FIRST STEPS", "WATCH OUT"],
      [["Narrow, regular (SVT)", "Vagal maneuvers → adenosine 6 mg, then 12 mg", "Warn the patient; record the strip"],
       ["Narrow, irregular (AFib)", "Rate control: beta-blocker or CCB", "Avoid in pre-excitation / HF (CCB)"],
       ["Wide, regular", "Adenosine *only* if monomorphic; antiarrhythmic infusion", "Expert consult"],
       ["Wide, irregular", "Expert consult", "*No* AV-nodal blockers if pre-excited"]])],
    [("kicker", "ONE-LINER"), ("title", "Unstable = *electricity*.\nStable = *diagnosis first*.", 80),
     ("body", "The 12-lead is your friend when you have the time. The defibrillator is your friend when you don't.")],
    [("cta",)],
]}

C3 = {"id": "C3_post_rosc_targets", "slides": [
    [("kicker", "AHA 2025  ·  POST-ARREST CARE"), ("title", "You got *ROSC.*\nNow what?", 92),
     ("ecg", "sinus", {"hr": 96}, "II  ·  ROSC  ·  HR 96", G, 230, 4),
     ("body", "The targets that protect the heart and brain after the code."), ("swipe",)],
    [("kicker", "THE NUMBERS", CYAN),
     ("stats", [("MAP", "at least 65", "mmHg · treat hypotension early (fluids, vasopressors)"),
                ("SpO2", "90–98%", "Titrate O2 down. Avoid hypoxia *and* hyperoxia"),
                ("PaCO2", "35–45", "mmHg · normocapnia. Don't hyperventilate"),
                ("Temp", "32–37.5 °C", "Deliberate temperature control if not following commands"),
                ("Duration", "36 h+", "Temperature control for at least 36 hours")])],
    [("kicker", "AIRWAY & BREATHING"), ("title", "Secure it. *Measure* it.", 76),
     ("bullets", ["Advanced airway if needed, confirmed with *waveform capnography*",
                  "Titrate FiO2 to SpO2 *90–98%*",
                  "Set rate/volume for *PaCO2 35–45*; check an ABG",
                  "Avoid the post-code reflex of bagging too fast"], 40)],
    [("kicker", "CIRCULATION"), ("title", "Find the *why*,\nstarting with the heart", 74),
     ("bullets", ["*12-lead ECG* as soon as possible",
                  "STEMI (or suspected cardiac cause with shock / instability) → *emergent cath lab*",
                  "Keep MAP *at least 65*; arterial line when you can",
                  "Work the *H's & T's*: labs, K+, glucose, ultrasound"], 40)],
    [("kicker", "THE BRAIN", CYAN), ("title", "Not following commands?", 74),
     ("bullets", ["Start *deliberate temperature control*: constant 32–37.5 °C",
                  "Keep it going *at least 36 h*; prevent fever",
                  "No routine *prehospital* cooling with cold IV fluids",
                  "Watch for seizures: get an *EEG*"], 40),
     ("callout", "Don't call it early: neuroprognosis is *multimodal* and delayed until at least *72 h* after normothermia.", YELLOW)],
    [("cta",)],
]}

C4 = {"id": "C4_high_quality_cpr_numbers", "slides": [
    [("kicker", "BLS IS THE BACKBONE OF ACLS"), ("title", "High-quality CPR,\n*by the numbers*", 88),
     ("ecg", "cpr", {}, "II  ·  COMPRESSIONS IN PROGRESS", G, 230, 4), ("swipe",)],
    [("kicker", "COMPRESSIONS", CYAN),
     ("stats", [("Rate", "100–120/min", "Faster isn't better: depth drops above 120"),
                ("Depth", "2–2.4 in", "5–6 cm in adults. Firm surface"),
                ("Recoil", "Full", "Don't lean between compressions"),
                ("Pauses", "under 10 s", "Pulse checks, shocks, airway: keep them short"),
                ("CCF", "as high as possible", "Chest compression fraction: *at least 60%*")])],
    [("kicker", "BREATHS", CYAN),
     ("stats", [("No advanced airway", "30 : 2", "Each breath over 1 s, just enough for chest rise"),
                ("Advanced airway", "1 every 6 s", "10 breaths/min with *continuous* compressions"),
                ("Biggest error", "Too many", "Hyperventilation cuts venous return and coronary flow")])],
    [("kicker", "TEAM MOVES"), ("title", "Fatigue is invisible,\nuntil depth drops", 74),
     ("bullets", ["Switch compressors *every 2 min* (or sooner)",
                  "Swap at the rhythm check, in *under 5 s*",
                  "Charge the defibrillator *during* compressions",
                  "Use a metronome or feedback device"], 40)],
    [("kicker", "YOUR LIVE SCORE", YELLOW), ("title", "Watch the *EtCO2*", 80),
     ("ecg", "sequence", {"parts": [("cpr", 3, {}), ("cpr", 3, {})]}, "II  ·  CPR", G, 170, 4),
     ("bullets", ["*Under 10 mmHg* → improve compressions now",
                  "Abrupt, sustained rise to *35–40+ mmHg* → think ROSC"], 40)],
    [("cta",)],
]}

C5 = {"id": "C5_acls_drug_doses", "slides": [
    [("kicker", "SAVE FOR YOUR MEGACODE"), ("title", "ACLS drug doses:\nthe *cheat sheet*", 90),
     ("ecg", "vfib", {}, "II  ·  VF", G, 220, 4),
     ("body", "Adult doses from the AHA ACLS algorithms. Always verify with your institution."), ("swipe",)],
    [("kicker", "CARDIAC ARREST"),
     ("stats", [("Epinephrine", "1 mg IV/IO", "Every 3–5 min. PEA/asystole: *ASAP*. VF/pVT: after initial shocks fail"),
                ("Amiodarone", "300 mg", "Then *150 mg*. Shock-refractory VF / pVT"),
                ("or Lidocaine", "1–1.5 mg/kg", "Then *0.5–0.75 mg/kg*"),
                ("Vasopressin", "Not a substitute", "Don't use it in place of epinephrine")])],
    [("kicker", "BRADYCARDIA", CYAN),
     ("stats", [("Atropine", "1 mg IV", "Every 3–5 min, *max 3 mg*. Often fails in high-grade AV block"),
                ("Epinephrine drip", "2–10 mcg/min", "Titrate to response"),
                ("Dopamine drip", "5–20 mcg/kg/min", "Titrate to response"),
                ("If drugs fail", "Pace", "Transcutaneous pacing; confirm *mechanical* capture")])],
    [("kicker", "TACHYCARDIA (WITH A PULSE)", CYAN),
     ("stats", [("Adenosine", "6 mg → 12 mg", "Rapid push + *20 mL flush*. Regular narrow (or regular monomorphic wide)"),
                ("Amiodarone", "150 mg / 10 min", "Stable wide-complex; repeat as needed"),
                ("Procainamide", "20–50 mg/min", "Stop at hypotension, QRS +50%, or 17 mg/kg. Avoid with long QT / HF")])],
    [("kicker", "SPECIAL SITUATIONS", YELLOW),
     ("stats", [("Magnesium", "1–2 g IV", "Torsades de pointes (long QT)"),
                ("Calcium chloride", "10% · 1 g", "Hyperkalemia or calcium-channel blocker toxicity"),
                ("Sodium bicarb", "1 mEq/kg", "*Not routine.* HyperK, TCA overdose, severe acidosis"),
                ("Dextrose + insulin", "Shift K+", "Hyperkalemia: pair with glucose checks")])],
    [("cta",)],
]}

C6 = {"id": "C6_megacode_mistakes", "slides": [
    [("kicker", "MEGACODE TESTING"), ("title", "6 mistakes that\n*fail* megacodes", 96),
     ("ecg", "vt", {"hr": 176}, "II  ·  PULSELESS VT", RED, 220, 4),
     ("body", "Instructors see these every class. Don't be the example."), ("swipe",)],
    [("kicker", "MISTAKE 1"), ("title", "Checking the rhythm\nright after the shock", 66),
     ("wrongright", "Shock → stare at the monitor → check a pulse", "Shock → *resume CPR immediately* for 2 minutes, then check")],
    [("kicker", "MISTAKE 2"), ("title", "The 20-second\npulse check", 66),
     ("wrongright", "Long pauses while someone hunts for a pulse", "Rhythm + pulse check in *under 10 s*. Unsure? Resume CPR")],
    [("kicker", "MISTAKE 3"), ("title", "Wrong defib mode", 72),
     ("wrongright", "SYNC on for VF (it may never fire) · or no SYNC for unstable AFib with a pulse",
      "Pulseless VF/pVT: *unsynchronized*. Unstable tachy *with a pulse*: *SYNC*, re-checked each shock")],
    [("kicker", "MISTAKE 4"), ("title", "Epi at the\nwrong time", 72),
     ("wrongright", "Delaying epi in asystole/PEA · or giving it before any shock in VF",
      "Non-shockable: *epi ASAP*. Shockable: epi *after initial shocks fail*, then every 3–5 min")],
    [("kicker", "MISTAKE 5"), ("title", "Shocking a\nflat line", 72),
     ("wrongright", "Defibrillating asystole or PEA", "*CPR + epinephrine*, then hunt the *H's & T's*. Check leads & gain on a flat line")],
    [("kicker", "MISTAKE 6"), ("title", "The silent leader", 72),
     ("wrongright", "Orders into the air, no one confirms, no plan out loud",
      "*Closed-loop*: name a person, give the order, hear it back. Summarize every 2 min")],
    [("cta",)],
]}

C7 = {"id": "C7_av_blocks_4_strips", "slides": [
    [("kicker", "RHYTHM RECOGNITION"), ("title", "4 heart blocks.\n*4 strips.*", 96),
     ("body", "Learn to spot them in 60 seconds. Look at the *PR interval* first, then ask: did every P get a QRS?"),
     ("ecg", "mobitz1", {}, "II  ·  ?", G, 220, 6), ("swipe",)],
    [("kicker", "1ST DEGREE", CYAN), ("title", "PR is *long*,\nbut every P conducts", 70),
     ("ecg", "first_degree", {}, "II  ·  PR 0.32 s", G, 250, 5),
     ("bullets", ["PR *over 0.20 s* (one big box), constant", "1 P : 1 QRS", "Usually benign; watch for progression"], 38)],
    [("kicker", "2ND DEGREE · TYPE I (WENCKEBACH)", CYAN), ("title", "Longer, longer,\nlonger, *drop*", 70),
     ("ecg", "mobitz1", {}, "II  ·  GROUPED BEATING", G, 250, 6),
     ("bullets", ["PR *progressively lengthens* until a QRS drops", "Usually at the AV node", "Often benign; treat if symptomatic"], 38)],
    [("kicker", "2ND DEGREE · TYPE II (MOBITZ II)"), ("title", "Same PR,\nthen a *sudden drop*", 70),
     ("ecg", "mobitz2", {}, "II  ·  DROPPED QRS", G, 250, 6),
     ("bullets", ["PR *stays constant*, then a P with no QRS", "Below the AV node, often wide QRS",
                  "Can progress to complete block: *pads on, prepare to pace*"], 38)],
    [("kicker", "3RD DEGREE (COMPLETE)"), ("title", "P's and QRS's\n*ignore each other*", 70),
     ("ecg", "chb", {}, "II  ·  AV DISSOCIATION", RED, 250, 6),
     ("bullets", ["P waves march through at their own rate", "Slow escape rhythm, often *wide*",
                  "Symptomatic → *pace*; atropine often won't work"], 38)],
    [("kicker", "SIDE BY SIDE", YELLOW),
     ("table", ["BLOCK", "PR INTERVAL", "DROPPED QRS?"],
      [["1st degree", "Long, constant", "Never"],
       ["2nd, Type I", "Gets longer each beat", "Yes, after the longest PR"],
       ["2nd, Type II", "Constant", "Yes, suddenly"],
       ["3rd degree", "No relationship", "P's and QRS's independent"]]),
     ("callout", "Symptomatic brady: atropine *1 mg* (max 3 mg) → pacing or epi / dopamine drip. High-grade blocks: go to *pacing* early.", CYAN)],
    [("cta",)],
]}

CAROUSELS = [C1, C2, C3, C4, C5, C6, C7]
